### ISSUE TITLE
optional argument of the form `[ {$]$} ]`

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#129]
hi

plastex does not parse correctly the following type of input

> \documentclass{article}
> \usepackage{amsthm}
> \newtheorem{Theorem}{Teorema}
> \begin{document}
> \begin{Theorem}[The argopt contains {$]\int_\infty$} the square bracket]
> \end{Theorem}
> \end{document}

it thinks that the optional argument ends before \int

the following patch fixes this 

bye

a.

[argpars.txt](https://github.com/plastex/plastex/files/3907389/argpars.txt)

**Comment by PatrickMassot** [comment]
@mennucc I merged this one month ago, but I just reverted the merge since your patch was successful on weird inputs but not on standard ones like 
```latex
\begin{proof}[Proof of Theorem~\ref{main}]
...
\end{proof}
```
I reverted because I have no idea when I'll have time to think about having a version which is correct both for weird cases and standard ones, but I would happily merge a new version from you that covers both. Thanks again for trying to improve this. Parsing TeX is really tricky...
