### ISSUE TITLE
travis-ci reports are broken

### ISSUE THREAD

**Issue by llimeht** [plastex/plastex#134]
PRs are being tested on travis-ci but the results of the tests are not being reported back. 

Reading https://github.com/travis-ci/travis-ci/issues/9440 it seems that a repository owner might need to turn it off and on again at both github and travis ends.

**Comment by PatrickMassot** [comment]
Thanks for your report. I tried to click a couple of random buttons but it probably didn't fix anything. The issue you linked to is one year and half old, and much has changed since then. In particular Travis seems to be migrating to a new way of interacting with GitHub, and I cannot connect what I read in that issue and what is currently visible.

**Comment by rolandweber** [comment]
Just noticed that, too. Even without PRs, in the commit list, I don't see the green checkmark for builds of recent commits, although those from two months ago are still showing.

Travis seems to have lost some level of access, because I cannot enable integration for a new project. Nor can I disable the one for the old project.

**Comment by tiarno** [comment]
I can delete the Travis connection if you want.

**Comment by rolandweber** [comment]
Thanks, but that doesn't seem to be necessary. I logged out of Travis and back in, then the permission problem was gone. I followed these instructions to reset the integration:
https://travis-ci.community/t/pushes-wont-trigger-new-builds-anymore-after-the-project-has-been-inactive-for-a-long-time/5716/2
I hope things are working again now. I'll see next time when I push a commit :-)

**Comment by PatrickMassot** [comment]
This is no longer relevant since Travis doesn't exist anymore.
