### ISSUE TITLE
mathjax and < >

### ISSUE THREAD

**Issue by mennucc** [plastex/plastex#143]
Hi.

 When math contains < and > , and html5 and mathjax is used, this causes problems, since the browser fails in parsing the html, and mathjax cannot represent the result.

Moreover mathjax by default works on inline math enclosed in `\(...\)` and not `$...$`  .  The documentation [1] recommends against parsing `$`

The attached patch fixes both problems

- it outputs inline math enclosed in  `\(...\)` 

- it converts < and > to `\lt` and `\gt` as suggested in [1] 

 while still being compatible with the xhtml renderer ; but I did not test its compatibility with all other renderers 

[pat_mathjax.txt](https://github.com/plastex/plastex/files/4142708/pat_mathjax.txt)

a.

ps: I find the options `--dollars, --no-dollars` to be useless... the point is not _using dollars_ , the point is _math formulas should be displayed in html as math formulas not as TeX_

[1] https://readthedocs.org/projects/mathjax/downloads/pdf/v2.5-latest/

**Comment by 0-andy-0** [comment]
Many thanks, I have applied your patch on my machine and it fixes scores of stupid problems in my notes that could not be fixed in any other way.  Typical example from the proof that p choose k is a multiple of p:

`The factors in the denominator are $<p$, so $p$ is not cancelled out.`

rendered as

`The factors in the denominator are $`



Can I ask the patch be merged asap.

Please please please!

**Comment by dalcde** [comment]
This will not be an issue if we migrate to server-side rendering that turns the math environments into html directly. In any case, I think this should be dealt with on the renderer side
