### ISSUE TITLE
plasTeX fails on empty ref 

### ISSUE THREAD

**Issue by ugoertz** [plastex/plastex#254]
This LaTeX file
```latex
\documentclass{article}
\begin{document}
\ref{}
\end{document}
```
works with pdflatex (with a warning about the undefined reference, of course), but plasTeX fails with a `jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'label'`. Since I had started with a "real" document it took me some time to track this down to the above cause.
I am not sure how/where (or even if) this should be fixed - of course the TeX source is in some sense erroneous.

**Comment by PatrickMassot** [comment]
Thanks for the report. Erroneous input is part of life, it shouldn't crash plasTeX. I pushed a global fix at 3c17dcb63c8e57cee27cebc47fcf2bc63680660e, catching Jinja2 template exceptions. I also fixed the \ref template at 62789f3bd1604572dc9610e79d672326ab62789c so that it prints `??` in that case (as you would expect in pdf).
