### ISSUE TITLE
Bibliography and figures problems

### ISSUE THREAD

**Issue by samtsevich** [plastex/plastex#260]
[Archive.zip](https://github.com/plastex/plastex/files/6617192/Archive.zip)

Here is the inputs to represent the problems.

First, **plastex** somehow badly parse paths to images - see an error while running `plastex uspex_manual_english.tex`.
I checked the path to the image and it somehow looks like `<plasTeX.TeXFragment object at 0x113b5ef40>`.
This problem happens in chapter 5 and even if I comment problematic images it still does not provide reasonable bibliography.

Seems that it is easy to fix for you.
I hope you can do it.

**Comment by samtsevich** [comment]
However, when I tried to convert this sources into pdf by TexMaker on my MacOS - it works.

**Comment by PatrickMassot** [comment]
I appreciate that you included an example, since this is a clear improvement compared to your earlier bug report. The next trick is to include a *minimal* example. Let's think about this: you have dozens of pictures that work (or at least don't trigger any error message) and suddenly some figure doesn't work. How can you deduce from that "plastex somehow badly parse paths to image"? Surely that figure had a weird path? No, it hasn't. What's the next step then? Should you dump thousands of lines of tex code to maintainers of platex? No. *Your* job was to cut your file down until you can reproduce the error with a ten lines long tex file.

Since I know you already made an effort by providing your file, and because I'm too nice for my own good, I did your job. I started by removing all chapters except for chapter 5 and then I removed lines from that chapter by dichotomy. I ended up with:
```latex
\documentclass{article}
                                                                                       
\usepackage{graphicx}
 
\begin{document}                                               
B$_2$O$_3$, B$_4$O$_6$, B$_6$O$_9$, B$_8$O$_1$$_2$

\includegraphics[scale=0.6]{pic/evolutionary_metadynamics.png}           
\end{document}
```
So this could have been your bug report. Except that of course at that point you would have realized the problem hasn't much to do with `\includegraphics`. plasTeX simply gets utterly confused by the first line. How can you think this line is a good idea? Especially the `O$_1$$_2$` part?! I understand that TeX can parse that. It can parse many evil things, and that's a major flaw of TeX that caused a lot of suffering in the last 40 years, because it always backfires at some point. Adding this kind of "feature" to plasTeX has negative priority.
