### ISSUE TITLE
How to define a package in a \documentclass macro

### ISSUE THREAD

**Issue by greatvwei** [plastex/plastex#261]
There is my tex file:
```tex
\documentclass{example}
\begin{document}

\begin{figure*}[!htb]
\includegraphics[width=160mm]{figure1.jpg}
\caption{Color online.}
\label{fig1}
\end{figure*}

\end{document}
```
while there is "\RequirePackage{graphicx}" in example.cls, could you tell me how to define this package in example.py? Thank you.

**Comment by PatrickMassot** [comment]
I'm sorry, I don't understand this question. Could you please provide the relevant part of your `example.cls` file? As usual with any bug report, what is needed is a minimal reproducible example, see [this discussion](https://stackoverflow.com/help/minimal-reproducible-example) for instance.

**Comment by greatvwei** [comment]
Here is the relevant part of my example.cls:
`\NeedsTeXFormat{LaTeX2e}[2007/10/19]
\ProvidesClass{example}
 
\LoadClass[cs4size,a4paper,fancyhdr,fntef, UTF8]{ctexbook}[2007/10/19]
 
\RequirePackage{graphicx}
 
\endinput`
and what my question is that how can I define the package like "\RequirePackage{graphicx}" in example.py?

**Comment by PatrickMassot** [comment]
I see you are a GitHub beginner, so let me help you a bit more. When you want to quote several lines of code you need to start a newline with three backticks and a language name, python or tex for instance, then a newline, your code, a newline and again three backticks. You can use the Preview tab on top of your message to double-check it works before posting. For instance compare the following with your first message.
```tex
\documentclass{example}
\begin{document}

\begin{figure*}[!htb]
\includegraphics[width=160mm]{figure1.jpg}
\caption{Color online.}
\label{fig1}
\end{figure*}

\end{document}
```
Then your minimal reproducible example is not reproducible since it refers to a mysterious `ctexbook` class that is not present in a standard tex setup.

That being said, I think I understand your question now. Your `example.py` can start with
```python
from plasTeX.Packages.article import *
from plasTeX.Packages.graphicx import *
```
This assumes your class extends `article` instead of the mysterious `ctexbook`.

**Comment by greatvwei** [comment]
Here is the relevant part of my example.cls:
`\NeedsTeXFormat{LaTeX2e}[2007/10/19]
\ProvidesClass{example}
 
\LoadClass[cs4size,a4paper,fancyhdr,fntef, UTF8]{ctexbook}[2007/10/19]
 
\RequirePackage{graphicx}
 
\endinput```
and what my question is that how can I define the package like "\RequirePackage{graphicx}" in example.py?

**Comment by greatvwei** [comment]
Oh, yes! I got it! And it words now.
Thank you so much and  happy Dragon Boat Festival!
