### ISSUE TITLE
Bibliography with natbib problem

### ISSUE THREAD

**Issue by samtsevich** [plastex/plastex#263]
Once again I write you to describe the problem with natbib usage in TeX while converting to the html.
Below you will find 2 file that represent the problem.

If you will try to run:
`plaster tmp.tex`
you will find this error.

Hope that you can fix that easily.

UPD. I did provide a wrong archive with necessary files. Now, you can find proper one below of this comment.
[Archive.zip](https://github.com/plastex/plastex/files/6676051/Archive.zip)

**Comment by efiminem** [comment]
This issue is fixed in #265

**Comment by PatrickMassot** [comment]
I don't see how this test file with one bibliographic reference can be a test for a bibliography **sorting** function. I already told you [one year and half ago](https://github.com/plastex/plastex/issues/234#issuecomment-750855428) that modifying this function so that it compiles was trivial. But I didn't want to merge code that I have no idea what it is meant to do and whether it does it. And I don't want to spend time trying to understand what a super obsolete LaTeX package is meant to do.
